CREATE SCHEMA QUADRADO; 

USE QUADRADO; 

CREATE TABLE AUTOR
(
	IDAUTOR INT NOT NULL,
    NOMEAUTOR VARCHAR(100) NOT NULL,
    primary key (IDAUTOR)
);

CREATE TABLE LIVRO
(
	IDLIVRO INT NOT NULL,
    DESC_TITULO VARCHAR(200) NOT NULL,
    IDAUTOR INT,
    constraint FK_AUTOR_LIVRO foreign key (IDAUTOR) references AUTOR (IDAUTOR)
);

CREATE TABLE ALUGUEL
(
	IDALUGUEL INT NOT NULL auto_increment,
	DATA_ALUGUEL DATE NOT NULL,
    primary key (IDALUGUEL)
);

ALTER TABLE LIVRO
ADD PRIMARY KEY (IDLIVRO);

ALTER TABLE ALUGUEL
ADD COLUMN IDLIVRO INT;

-- COMANDO PARA ADD CHAVE ESTRANGEIRA
ALTER TABLE ALUGUEL
ADD constraint FK_ALUGUEL_LIVRO FOREIGN KEY (IDLIVRO) references LIVRO (IDLIVRO);

