CREATE DATABASE IF NOT EXISTS SYBANK; -- criar banco de dados

USE SYBANK; -- CONECTAR NO BANCO DE DADOS CRIADO

CREATE TABLE IF NOT EXISTS PESSOA
(
	IDPESSOA INT NOT NULL,
    NOMEPESSOA VARCHAR(100) NOT NULL,
    NUMTELEFONE VARCHAR(11) NOT NULL,
    EMAILPESSOA VARCHAR (100) NOT NULL,
    PRIMARY KEY (IDPESSOA)
);

 -- ENDEREÇO: SQS 415 BLOCO G AP 200 ASA SUL, BRASÍLIA - DF CEP: 71000-598
 -- CIDADE
 -- ESTADO
 -- BAIRRO
 -- LOGRADOURO
 -- NUMERO (PESSOA)
 -- COMPLEMENTO (PESSOA)
 
 CREATE TABLE IF NOT EXISTS SYBANK.ESTADO
 (
	CODUF CHAR(2) NOT NULL,
    DESCUF VARCHAR(50) NOT NULL,
    PRIMARY KEY (CODUF)
 );
 
 CREATE TABLE IF NOT EXISTS SYBANK.CIDADE
 (
	CODUF CHAR(2) NOT NULL,
    IDCIDADE SMALLINT NOT NULL,
    NOMECIDADE VARCHAR(100) NOT NULL,
    PRIMARY KEY (IDCIDADE),
    CONSTRAINT FK_ESTADO_CIDADE foreign key (CODUF) references SYBANK.ESTADO (CODUF)
 ); 
 
 -- Para ter uma chave estrangeira cadastrada:
   -- 1º Se ela for PK na tabela pai,
   -- 2º O tipo de dado precisa ser igual,
   -- 3º A chave estrangeira pode ser nula (NULL). 

Create Table if not exists SYBANK.BAIRRO
(
	IDBAIRRO INT NOT NULL,
    IDCIDADE SMALLINT NOT NULL,
    DESCBAIRRO VARCHAR(100) NOT NULL,
    PRIMARY KEY (IDBAIRRO),
    CONSTRAINT FK_CIDADE_BAIRRO FOREIGN KEY (IDCIDADE) REFERENCES SYBANK.CIDADE (IDCIDADE)
);

CREATE TABLE IF NOT EXISTS SYBANK.LOGRADOURO
(
	NUMCEP CHAR(8) NOT NULL,
    IDBAIRRO INT NOT NULL,
    DESCLOGRADOURO VARCHAR(200) NOT NULL,
    PRIMARY KEY (NUMCEP),
    CONSTRAINT FK_BAIRRO_LOGRADOURO foreign key (IDBAIRRO) references SYBANK.BAIRRO (IDBAIRRO)
);
 
ALTER TABLE SYBANK.PESSOA
ADD COLUMN NUMENDERECO VARCHAR(10) NOT NULL;
 
ALTER TABLE SYBANK.PESSOA
ADD COLUMN DESC_COMPLEMENTO VARCHAR(100);

ALTER TABLE SYBANK.PESSOA
ADD COLUMN NUMCEP CHAR(8) NOT NULL,
ADD CONSTRAINT FK_LOGRADOURO_PESSOA foreign key (NUMCEP) references SYBANK.LOGRADOURO (NUMCEP);

ALTER table SYBANK.PESSOA
DROP COLUMN NUMENDERECO,
DROP COLUMN DESC_COMPLEMENTO;

ALTER table SYBANK.PESSOA
ADD COLUMN NUMENDERECO VARCHAR (10) NOT NULL,
ADD COLUMN DESC_COMPLEMENTO VARCHAR(100);

 CREATE TABLE IF NOT exists SYBANK.PESSOAFISICA
 (
	IDPESSOA INT NOT NULL,
    NUMCPF CHAR(11) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    NUMRG VARCHAR(30) NOT NULL,
    PRIMARY KEY (NUMCPF),
    constraint FK_PESSOA_PESSOAFISICA foreign key (IDPESSOA) references SYBANK.PESSOA (IDPESSOA)
 );

ALTER TABLE SYBANK.PESSOAFISICA 
DROP FOREIGN KEY FK_PESSOA_PESSOAFISICA;

ALTER TABLE SYBANK.PESSOAFISICA
MODIFY IDPESSOA INT NOT NULL AUTO_INCREMENT;

CREATE TABLE IF NOT EXISTS SYBANK.PESSOAJURIDICA
(
	NUMCNPJ CHAR(14) NOT NULL,
    IDPESSOA INT NOT NULL,
    NOMEFANTASIA VARCHAR (100),
    DATAFUNDACAO DATE NOT NULL,
    NUM_INS_ESTADUAL VARCHAR(50),
    PRIMARY KEY (NUMCNPJ),
    CONSTRAINT FK_PESSOA_PESSOAJURIDICA foreign key (IDPESSOA) references SYBANK.PESSOA (IDPESSOA)
);

-- TIPO DE CONTA
CREATE TABLE IF NOT EXISTS SYBANK.TIPOCONTA
(
	IDTIPOCONTA INT NOT NULL,
    DESCTIPOCONTA VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDTIPOCONTA)
);

-- CONTA
CREATE TABLE IF NOT EXISTS SYBANK.CONTA
(
	IDCONTA INT NOT NULL,
    IDTIPOCONTA INT NOT NULL,
    NUMCONTA VARCHAR(20) NOT NULL,
    NUMAGENCIA VARCHAR(10) NOT NULL,
    SALDO DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (IDCONTA),
    CONSTRAINT FK_TIPOCONTA_CONTA FOREIGN KEY (IDTIPOCONTA) REFERENCES SYBANK.TIPOCONTA (IDTIPOCONTA)
);

-- RELAÇÃO PESSOA E CONTA
CREATE TABLE IF NOT EXISTS SYBANK.PESSOA_CONTA
(
	IDPESSOA INT NOT NULL,
    IDCONTA INT NOT NULL,
    PRIMARY KEY (IDPESSOA),
    CONSTRAINT FK_PESSOA_CONTA_PESSOA FOREIGN KEY (IDCONTA) REFERENCES SYBANK.CONTA (IDCONTA)
);

-- TIPO DE TRANSAÇÃO
CREATE TABLE IF NOT EXISTS SYBANK.TIPOTRANSACAO
(
	IDTIPOTRANSACAO INT NOT NULL,
    DESCTRANSACAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDTIPOTRANSACAO)
);

-- TRANSAÇÃO 
CREATE TABLE IF NOT EXISTS SYBANK.TRANSACAO
(
	IDTRANSACAO INT NOT NULL,
    IDTIPOTRANSACAO INT NOT NULL,
    IDCONTAORIGEM INT NOT NULL,
    IDCONTADESTINO INT NOT NULL,
    VALOR DECIMAL (15,2) NOT NULL,
    DATATRANSACAO DATE NOT NULL,
    DESCRICAO VARCHAR (100),
    PRIMARY KEY (IDTRANSACAO),
    CONSTRAINT FK_TRANSACAO_TIPO FOREIGN KEY (IDTIPOTRANSACAO) REFERENCES SYBANK.TIPOTRANSACAO (IDTIPOTRANSACAO),
    CONSTRAINT FK_TRANSACAO_CONTAORIGEM FOREIGN KEY (IDCONTAORIGEM) REFERENCES SYBANK.CONTA (IDCONTA),
    CONSTRAINT FK_TRANSACAO_CONTADESTINO FOREIGN KEY (IDCONTADESTINO) REFERENCES SYBANK.CONTA (IDCONTA)
);

-- EXTRATO
CREATE TABLE IF NOT EXISTS SYBANK.EXTRATO
(
	IDEXTRATO INT NOT NULL,
    IDCONTA INT NOT NULL,
    IDTRANSACAO INT NOT NULL,
    SALDOANTERIOR DECIMAL(15,2),
    SALDOATUAL DECIMAL(15,2),
    PRIMARY KEY (IDEXTRATO),
    CONSTRAINT FK_EXTRATO_CONTA FOREIGN KEY (IDCONTA) REFERENCES SYBANK.CONTA (IDCONTA),
    CONSTRAINT FK_EXTRATO_TRANSACAO FOREIGN KEY (IDTRANSACAO) REFERENCES SYBANK.TRANSACAO (IDTRANSACAO)
);

-- CARTÃO
CREATE TABLE IF NOT EXISTS SYBANK.CARTAO
(
	IDCARTAO INT NOT NULL,
    IDCONTA INT NOT NULL,
    NUMCARTAO VARCHAR(20) NOT NULL,
    TIPOCARTAO VARCHAR(20) NOT NULL,
    LIMITE_TOTAL DECIMAL(15,2),
    LIMITE_DISPONIVEL DECIMAL(15,2),
    PRIMARY KEY (IDCARTAO),
    CONSTRAINT FK_CARTAO_CONTA FOREIGN KEY (IDCONTA) REFERENCES SYBANK.CONTA (IDCONTA)
);

-- FATURA 
CREATE TABLE IF NOT EXISTS SYBANK.FATURA
(
	IDFATURA INT NOT NULL,
    IDCARTAO INT NOT NULL,
    VALORFATURA DECIMAL(15,2),
    DATAVENCIMENTO DATE,
    PRIMARY KEY (IDFATURA),
    CONSTRAINT FK_FATURA_CARTÃO FOREIGN KEY (IDCARTAO) REFERENCES SYBANK.CARTAO (IDCARTAO)
);

-- EMPRÉSTIMO
CREATE TABLE IF NOT EXISTS SYBANK.EMPRESTIMO
(
	IDEMPRESTIMO INT NOT NULL,
    IDPESSOA INT NOT NULL,
    IDCONTA INT NOT NULL,
    VALOR DECIMAL(15,2) NOT NULL,
    JUROS DECIMAL(5,2) NOT NULL,
    QTD_PARCELAS INT NOT NULL,
    PRIMARY KEY (IDEMPRESTIMO),
    CONSTRAINT FK_EMPRESTIMO_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES SYBANK.PESSOA (IDPESSOA),
    CONSTRAINT FK_EMPRESTIMO_CONTA FOREIGN KEY (IDCONTA) REFERENCES SYBANK.CONTA (IDCONTA)
);

-- PARCELA
CREATE TABLE IF NOT EXISTS SYBANK.PARCELA
(
	IDPARCELA INT NOT NULL,
    IDEMPRESTIMO INT NOT NULL,
    NUMPARCELA INT NOT NULL,
    VALORPARCELA DECIMAL(15,2) NOT NULL,
    DATAVENCIMENTO DATE NOT NULL,
    PRIMARY KEY (IDPARCELA),
    CONSTRAINT FK_PARCELA_EMPRESTIMO FOREIGN KEY (IDEMPRESTIMO) REFERENCES SYBANK.EMPRESTIMO (IDEMPRESTIMO)
);

ALTER TABLE SYBANK.CONTA ADD COLUMN STATUS VARCHAR(20); 

ALTER TABLE SYBANK.PESSOAFISICA
MODIFY IDPESSOA INT NOT NULL;

DROP TABLE IF EXISTS SYBANK.PESSOA_CONTA;

CREATE TABLE SYBANK.PESSOA_CONTA (
    IDPESSOA INT NOT NULL,
    IDCONTA INT NOT NULL,
    PRIMARY KEY (IDPESSOA, IDCONTA),
    CONSTRAINT FK_PC_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES SYBANK.PESSOA(IDPESSOA),
    CONSTRAINT FK_PC_CONTA FOREIGN KEY (IDCONTA) REFERENCES SYBANK.CONTA(IDCONTA)
); 

ALTER TABLE SYBANK.EXTRATO
ADD COLUMN DATACRIACAO TIMESTAMP;

ALTER TABLE SYBANK.PARCELA
ADD COLUMN STATUS VARCHAR(20),
ADD COLUMN DATA_PAGAMENTO DATE NULL;

ALTER TABLE SYBANK.FATURA
ADD COLUMN DATA_ABERTURA DATE,
ADD COLUMN STATUS VARCHAR(20);

ALTER TABLE SYBANK.TRANSACAO
ADD COLUMN TIPO_PAGAMENTO VARCHAR(20);

ALTER TABLE SYBANK.EXTRATO
MODIFY DATACRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE SYBANK.FATURA
DROP FOREIGN KEY FK_FATURA_CARTÃO;

ALTER TABLE SYBANK.FATURA
ADD CONSTRAINT FK_FATURA_CARTAO FOREIGN KEY (IDCARTAO) REFERENCES SYBANK.CARTAO (IDCARTAO);